.github/pull_request_template.md, .github/workflows/pr-check.yml, .github/workflows/zip-apps.yml, .husky/pre-commit, README.md, USER/_registry.json, package-lock.json, package.json
A few automation inclusions for gatekeeping, and documentation updates.
- Add husky pre-commit hooks, running Prettier code adjustments.
- Update app registry to include "Name".
- Update README documentation.
- Add GitHub Actions for: PR-Check, and App Folder Zip building.
=> Automation

README.md, USER/PipPong.js, USER/PipSnake.js, USER/_registry.json
Add a description of the app here.
=> [Game] Pip-Pong

USER/FileExplorer.js, USER/_registry.json
A lightweight file explorer for the Pip-Boy 3000 Mk V. Browse your device's file system and interact with files directly.
=> [APP] File Explorer

README.md, USER/FileExplorer.js, USER/PipPong.js, USER/PipSnake.js, USER/_registry.json
**File Explorer** → v1.0.0 → v1.0.1
=> [PATCH] Fix File Explorer in-app name & meta updates.

README.md, USER/FileExplorer.js, USER/_registry.json, package.json
Fix up the recursion error for directories nested > 2 deep.
=> [APP][BUG] File Explorer Recurssion Fix

USER/CustomRadio.js, USER/_registry.json
A custom music player that allows you to choose the music you want to play from the `/RADIO` directory without restriction.
https://github.com/user-attachments/assets/e602fe9f-f400-4d32-9737-55004ee21000
=> [APP] Custom Radio

USER/CustomRadio.js, USER/_registry.json
Add a description of the app here.
=> [APP][BUG] Custom Radio v1.1.0 - Fix up files playing randomly

USER/PipPong.js, USER/PipSnake.js, USER/_registry.json, docs/loader.css
Update Pip-Pong & Pip-Snake games.
=> [GAMES] Pip-Pong & Pip-Snake improvements.

README.md, docs/index.html, docs/loader.js
Modified loader behaviour to support uploading pre-boot apps (see https://log.robco-industries.org/log/entry016/)
=> add bootcode loading support

USER/ThemePicker.js, USER_BOOT/ui_color.js, registry.json
Added the custom UI theme picker and modified the UI Color bootapp to support it.
=> Ui_color_theme

registry.json
Fix description for Theme Picker
=> [APP] Fix description for Theme Picker

USER/AsteroPIPs.js, registry.json
Add a description of the app here, or any other relevant information.
- [N/A] Any additional items...
=> init AsteroPIPs , a quick benchmarking  and fun game. :)

USER/AsteroPIPs.js
A quick prettier code formatting run
=> [APP] AsteroPIPs - Prettier run

USER/VaultBreaker.js, registry.json
Vault Breaker is a breakout clone for the Pip-Boy 3000 Mk V.
- None
=> Added Vault Breaker

USER/Pip2048.js, registry.json
Add a description of the app here, or any other relevant information.
=> Init pip2048

USER/StatsDisplay.js, registry.json
Normalize paths to fix saving of stats # and custom stats.
=> [APP] Stats Display: Patch - Normalize paths

USER/StatsDisplay.js, registry.json
Final bugfix for stats display (i hope)
=> Stats Display 2.2.2: bugfix for perk select screen

USER/CustomRadio.js, USER_BOOT/CustomRadio.js, registry.json
Improvements, bug fixes, and polishing.
=> Custom Radio - v2.1.0

USER_BOOT/CustomRadio.js, registry.json
Custom Radio app improvements.
=> [APP] Custom Radio - v2.3.0

USER/ThemePicker.js, USER_BOOT/ThemePickerBootloader.js, registry.json
Theme Picker is a better theme picker than the built-in one, with more control and the ability to change the colour of the scan line.
=> Re-add theme picker :)

USER/Piptris.js, registry.json
A simple Tetris inspired game for the Pip-Boy 3000 Mk V.
=> [GAME] Piptris v1.0.0

USER_BOOT/ThemePickerBootloader.js, registry.json
Patched a small memory leak in themepicker.
=> theme picker bootloader app optimisation
